version: '3.9'
services:
  angular:
    build: 
      context: bank-app-ui
      args : ["rooturl=http://10.4.0.3:8080"]
    ports:
      - '8085:80'
    networks:
      bank_network:
        ipv4_address: 10.4.0.4
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: bank_mohamed
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - '3308:3306'
    networks:
      bank_network:
        ipv4_address: 10.4.0.2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
  
  spring:
    build:
      context: ./springsecsection9
    ports:
      - '8080:8080'
    environment:
      spring_datasource_url: "jdbc:mysql://db:3306/bank_mohamed"
    networks:
      bank_network:
        ipv4_address: 10.4.0.3
    depends_on:
      db:
        condition: service_healthy
networks:
  bank_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.4.0.0/16
          gateway: 10.4.0.1